{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.usbharu",
    "module": "yt-dlp-java",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yt-dlp-java-1.0.0.jar",
          "url": "yt-dlp-java-1.0.0.jar",
          "size": 8630,
          "sha512": "5563b27a45829ed7f0d55e7c6a8bfd3c5fd794e14d1101d1c09fab76c6ab106c22699562fa45082fc153255c0d75ea15dfede2bc5ba18fe2b14df8b2f9ab222c",
          "sha256": "ea99167ecbd0c4a9118b8063dfdbd32ea48cdd2af6adf456c61c540257dc8cf6",
          "sha1": "e8695a1b900fe9a5352e1be967cf2d0698b67679",
          "md5": "da71bb452d19cb9cf807401f48f662fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          }
        }
      ],
      "files": [
        {
          "name": "yt-dlp-java-1.0.0.jar",
          "url": "yt-dlp-java-1.0.0.jar",
          "size": 8630,
          "sha512": "5563b27a45829ed7f0d55e7c6a8bfd3c5fd794e14d1101d1c09fab76c6ab106c22699562fa45082fc153255c0d75ea15dfede2bc5ba18fe2b14df8b2f9ab222c",
          "sha256": "ea99167ecbd0c4a9118b8063dfdbd32ea48cdd2af6adf456c61c540257dc8cf6",
          "sha1": "e8695a1b900fe9a5352e1be967cf2d0698b67679",
          "md5": "da71bb452d19cb9cf807401f48f662fa"
        }
      ]
    }
  ]
}
